# Generated by Django 5.1.5 on 2025-02-16 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YogaPose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Moderate', 'Moderate'), ('Advanced', 'Advanced')], max_length=20)),
                ('reference_image', models.ImageField(upload_to='poses/')),
                ('reference_landmarks', models.JSONField(blank=True, default=list)),
                ('video_url', models.URLField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('restricted_for_injuries', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('level', models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Moderate', 'Moderate'), ('Advanced', 'Advanced')], max_length=10)),
                ('injury_history', models.TextField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
