# Generated by Django 5.1.5 on 2025-02-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_yogapose_video_url_yogapose_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='yogapose',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
