# Generated by Django 5.1.5 on 2025-04-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_yogapose_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='recommended_poses',
            field=models.ManyToManyField(blank=True, related_name='recommended_for_users', to='app1.yogapose'),
        ),
    ]
